server:
  port: 8089
spring:
  ai:
    openai:
      api-key: sk-fe75d1cf92314f1fb0ed50fb0f4cb7e7
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  # or ASYNC for reactive applications
        sse:
          connections:
            server1:
              url: http://127.0.0.1:8080
#              url: http://127.0.0.1:8080/mcp/tools  baseUrl + sse-endpoint
        toolcallback:
          enabled: true
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG